In [1]:
import chromadb, pandas as pd, sentence_transformers as st
import re, json

/Users/infibiss/Desktop/Fridge-Recipe-Detector/.venv/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
df1 = pd.read_csv('recipes_foodru_1.csv')
df1.head()

,id,title,url,recipe,time,count,ingredients,nutrients,allergy,category
0,0,Шулюм из свинины,https://food.ru/recipes/256847-shulium-iz-svininy,Ошибка,0,0.0,[],{},Ошибка,первые блюда
1,1,Окрошка с крабом на айране,https://food.ru/recipes/254067-okroshka-s-krab...,Ошибка,0,0.0,[],{},Ошибка,первые блюда
2,2,Окрошка с отварной говядиной на ряженке,https://food.ru/recipes/254072-okroshka-s-otva...,Ошибка,0,0.0,[],{},Ошибка,первые блюда
3,3,Окрошка с копченой курицей и нутом на белом квасе,https://food.ru/recipes/254135-okroshka-s-kopc...,Ошибка,0,0.0,[],{},Ошибка,первые блюда
4,4,Окрошка со щавелем и ветчиной на кефире,https://food.ru/recipes/254063-okroshka-so-shc...,Ошибка,0,0.0,[],{},Ошибка,первые блюда

## Обработка

In [3]:
df1 = df1[df1['time'] != 0]
df1.head()

,id,title,url,recipe,time,count,ingredients,nutrients,allergy,category
201,201,Сырный суп со скумбрией,https://food.ru/recipes/227818-syrnyi-sup-so-s...,Нарежьте бекон на небольшие кусочки. Разогрейт...,30,4.0,"[{'name': 'Консервированная скумбрия', 'qty': ...","{'Калории': '202,74', 'Белки': '12,75', 'Жиры'...","Белок коровьего молока, Ракообразные, Рыба",первые блюда
202,202,Густой суп из шампиньонов с сыром и брокколи,https://food.ru/recipes/176803-sup-iz-gribov-s...,Нарежьте шампиньоны пластинками. Обжарьте в ма...,30,3.0,"[{'name': 'Шампиньоны', 'qty': '4', 'grams': '...","{'Калории': '28,68', 'Белки': '1,33', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глютен",первые блюда
203,203,Как сварить любой суп,https://food.ru/recipes/197715-kak-svarit-liub...,"Положите в кастрюлю кусок мяса, залейте водой ...",100,4.0,"[{'name': 'Свинина на кости', 'qty': '300', 'g...","{'Калории': '165,85', 'Белки': '7,59', 'Жиры':...","Злаки, содержащие глютен",первые блюда
204,204,Суп из сома,https://food.ru/recipes/228166-sup-iz-soma,Положите стейки сома в кастрюлю. Вскипятите в ...,40,3.0,"[{'name': 'Сом морской', 'qty': '300', 'grams'...","{'Калории': '33,69', 'Белки': '2,12', 'Жиры': ...","Злаки, содержащие глютен, Рыба",первые блюда
205,205,Татарская лапша,https://food.ru/recipes/228087-tatarskaja-lapsha,"Взбейте куриные яйца с 0,5 ч.л. соли при помощ...",180,4.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '55,03', 'Белки': '3,73', 'Жиры': ...","Злаки, содержащие глютен, Яйцо",первые блюда

In [4]:
df2 = pd.read_csv('recipes_foodru_2.csv')
df2_valid = df2[df2['time'] != 0].copy()
df2_valid.head()

,id,title,url,recipe,time,count,ingredients,nutrients,allergy,category
0,0,Гнезда с тефтелями в томатном соусе,https://food.ru/recipes/257868-gnezda-s-teftel...,Крупно натрите морковь. Нарежьте лук кубиками ...,60,4.0,"[{'name': 'Фарш из свинины и говядины', 'qty':...","{'Калории': '163,32', 'Белки': '6,66', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глютен",вторые блюда
1,1,Тушеные баклажаны с фасолью,https://food.ru/recipes/257915-baklazhany-s-fa...,Отварите предварительно замоченную фасоль до г...,75,2.0,"[{'name': 'Баклажан', 'qty': '1', 'grams': '21...","{'Калории': '128,74', 'Белки': '4,77', 'Жиры':...",Кунжут,вторые блюда
2,2,Cалат из зеленого горошка с сырокопченым карпаччо,https://food.ru/recipes/258025-calat-iz-zeleno...,Нашинкуйте капусту полосками шириной 5–6 мм. Р...,10,4.0,"[{'name': 'Консервированный горошек', 'qty': '...","{'Калории': '55,05', 'Белки': '3,86', 'Жиры': ...","Горчица, Пищевые добавки",вторые блюда
3,3,Легкий салат с кукурузой,https://food.ru/recipes/255758-legkii-salat-s-...,"Положите яйца в кастрюлю, залейте их водой. По...",25,4.0,"[{'name': 'Салат–латук', 'qty': '1', 'grams': ...","{'Калории': '64,5', 'Белки': '3,69', 'Жиры': '...","Белок коровьего молока, Яйцо",вторые блюда
4,4,Фетучини карбонара,https://food.ru/recipes/257663-fetuchini-karbo...,Отварите фетучини в кипящей подсоленной воде д...,20,4.0,"[{'name': 'Паста фетучини', 'qty': '400', 'gra...","{'Калории': '410,84', 'Белки': '20,5', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда

In [5]:
# df3 = pd.read_csv('recipes_foodru_вторые блюда.csv')
# df3_valid = df3[df3['time'] != 0].copy()
# df3_valid.head()

FileNotFoundError: [Errno 2] No such file or directory: 'recipes_foodru_вторые блюда.csv'

In [33]:
# combined_df = pd.concat([df3_valid, df2_valid], ignore_index=True)
# final_df = combined_df.drop_duplicates(subset=['id'], keep='first')
# final_df.head(50)

,id,title,url,recipe,time,count,ingredients,nutrients,allergy,category
0,0,Гнезда с тефтелями в томатном соусе,https://food.ru/recipes/257868-gnezda-s-teftel...,Крупно натрите морковь. Нарежьте лук кубиками ...,60,4.0,"[{'name': 'Фарш из свинины и говядины', 'qty':...","{'Калории': '163,32', 'Белки': '6,66', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глютен",вторые блюда
1,1,Тушеные баклажаны с фасолью,https://food.ru/recipes/257915-baklazhany-s-fa...,Отварите предварительно замоченную фасоль до г...,75,2.0,"[{'name': 'Баклажан', 'qty': '1', 'grams': '21...","{'Калории': '128,74', 'Белки': '4,77', 'Жиры':...",Кунжут,вторые блюда
2,2,Cалат из зеленого горошка с сырокопченым карпаччо,https://food.ru/recipes/258025-calat-iz-zeleno...,Нашинкуйте капусту полосками шириной 5–6 мм. Р...,10,4.0,"[{'name': 'Консервированный горошек', 'qty': '...","{'Калории': '55,05', 'Белки': '3,86', 'Жиры': ...","Горчица, Пищевые добавки",вторые блюда
3,3,Легкий салат с кукурузой,https://food.ru/recipes/255758-legkii-salat-s-...,"Положите яйца в кастрюлю, залейте их водой. По...",25,4.0,"[{'name': 'Салат–латук', 'qty': '1', 'grams': ...","{'Калории': '64,5', 'Белки': '3,69', 'Жиры': '...","Белок коровьего молока, Яйцо",вторые блюда
4,4,Фетучини карбонара,https://food.ru/recipes/257663-fetuchini-karbo...,Отварите фетучини в кипящей подсоленной воде д...,20,4.0,"[{'name': 'Паста фетучини', 'qty': '400', 'gra...","{'Калории': '410,84', 'Белки': '20,5', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
5,5,Салат «Ацецили» с курицей,https://food.ru/recipes/255756-salat-acecili-s...,"Нарежьте дайкон соломкой, а болгарский перец —...",15,4.0,"[{'name': 'Куриная грудка', 'qty': '180', 'gra...","{'Калории': '51,76', 'Белки': '6,71', 'Жиры': ...","Белок коровьего молока, Горчица",вторые блюда
6,6,Шоколадные вареники с творогом и вишней,https://food.ru/recipes/257266-shokoladnye-var...,Всыпьте в миску с мукой какао-порошок и соль. ...,35,4.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '182,28', 'Белки': '7,33', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
7,7,Простой блинный торт с черникой,https://food.ru/recipes/256678-blinchiki-s-che...,Всыпьте сахар в молоко и разбейте туда же яйца...,70,6.0,"[{'name': 'Молоко', 'qty': '2.5', 'grams': '50...","{'Калории': '155,06', 'Белки': '4,64', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
8,8,Зеленый салат с семенами и орехами и мини-моца...,https://food.ru/recipes/255754-zelenyi-salat-s...,Порвите салатные листья руками на небольшие ку...,15,4.0,"[{'name': 'Салат–латук', 'qty': '1', 'grams': ...","{'Калории': '113,72', 'Белки': '5,41', 'Жиры':...","Белок коровьего молока, Кунжут",вторые блюда
9,9,Вареники с картошкой и грибами,https://food.ru/recipes/257256-Vareniki-s-kart...,"Всыпьте в миску с мукой 1 ч.л. соли, перемешай...",60,3.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '155,61', 'Белки': '4,68', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
10,10,Сырники с соусом из черной смородины,https://food.ru/recipes/256676-syrniki-s-chern...,"Положите смородину в сотейник, всыпьте сахар и...",30,3.0,"[{'name': 'Творог', 'qty': '300', 'grams': '30...","{'Калории': '139,19', 'Белки': '7,91', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
11,11,Куриные голени с фунчозой,https://food.ru/recipes/256671-kurinye-goleni-...,Натрите курицу приправой и дайте промариновать...,75,2.0,"[{'name': 'Куриная голень', 'qty': '4', 'grams...","{'Калории': '99,93', 'Белки': '6,6', 'Жиры': '...","Злаки, содержащие глютен, Кунжут, Соя",вторые блюда
12,12,Пышные оладьи с джемом,https://food.ru/recipes/257252-pyshnye-oladi-s...,"Разбейте яйца в миску, всыпьте к ним сахар и с...",75,10.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '205,01', 'Белки': '5,99', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
13,13,ПП-гуляш из говядины,https://food.ru/recipes/256668-pp-guljash-iz-g...,Нарежьте говядину небольшими кубиками.\nИзмель...,85,2.0,"[{'name': 'Говядина', 'qty': '500', 'grams': '...","{'Калории': '107,98', 'Белки': '7,98', 'Жиры':...",Нет,вторые блюда
14,14,Паста с клубникой,https://food.ru/recipes/257549-pasta-s-klubnikoi,Отложите ⅓ клубники для украшения. Соедините о...,70,4.0,"[{'name': 'Паста', 'qty': '200', 'grams': '200...","{'Калории': '123,47', 'Белки': '3,53', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
15,15,Тефтели с кабачком в духовке,https://food.ru/recipes/257163-tefteli-s-kabac...,Натрите кабачок. Чуть посолите и дайте постоят...,65,4.0,"[{'name': 'Свиной фарш', 'qty': '350', 'grams'...","{'Калории': '154,54', 'Белки': '9,76', 'Жиры':...","Злаки, содержащие глютен, Яйцо",вторые блюда
16,16,Блинчики с начинкой из творога,https://food.ru/recipes/247643-blinchiki-s-nac...,Вскипятите 100 мл воды. Выложите курагу в жаро...,50,12.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '180,16', 'Белки': '9,11', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
17,17,Паста алла Нерано,https://food.ru/recipes/257241-pasta-alla-nerano,Пропустите чеснок через пресс. Мелко натрите п...,35,3.0,"[{'name': 'Кабачок', 'qty': '2', 'grams': '600...","{'Калории': '377,93', 'Белки': '3,9', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глютен",вторые блюда
18,18,Запеканка из шампиньонов,https://food.ru/recipes/257161-zapekanka-iz-sh...,"Отварите картофель до готовности в кипящей, чу...",50,4.0,"[{'name': 'Картошка', 'qty': '3', 'grams': '36...","{'Калории': '158,17', 'Белки': '4,62', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глютен",вторые блюда
19,19,Грибы с сулугуни по-грузински,https://food.ru/recipes/256880-griby-s-sulugun...,Аккуратно удалите у каждого шампиньона ножку и...,40,2.0,"[{'name': 'Шампиньоны', 'qty': '6', 'grams': '...","{'Калории': '235,06', 'Белки': '10', 'Жиры': '...",Белок коровьего молока,вторые блюда
20,20,Радиатори с соусом из запеченных овощей,https://food.ru/recipes/257379-radiatore-c-pec...,Разогрейте духовку до 180 °С. Разрежьте болгар...,40,3.0,"[{'name': 'Паста', 'qty': '250', 'grams': '250...","{'Калории': '187,99', 'Белки': '4,37', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глютен",вторые блюда
21,21,Запеченные макароны «Зити» Кармелы Сопрано,https://food.ru/recipes/256573-zapechennye-mak...,Пропустите чеснок через пресс. Нарежьте лук ку...,90,6.0,"[{'name': 'Паста ригатони', 'qty': '500', 'gra...","{'Калории': '190,1', 'Белки': '10,64', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
22,22,Жареный рис,https://food.ru/recipes/256878-zharenyi-ris,"Разогрейте сковороду на среднем огне, растопит...",35,3.0,"[{'name': 'Рис длиннозерный', 'qty': '1', 'gra...","{'Калории': '120,56', 'Белки': '2,06', 'Жиры':...",Белок коровьего молока,вторые блюда
23,23,Зеленые сырники,https://food.ru/recipes/256571-zelenye-syrniki,Перетрите творог через сито.\nНе пропускайте э...,30,3.0,"[{'name': 'Творог', 'qty': '2.5', 'grams': '50...","{'Калории': '178,1', 'Белки': '14,09', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
24,24,Пельмени с бульоном в духовке,https://food.ru/recipes/256653-pelmeni-s-bulon...,"Выложите пельмени, не размораживая, в керамиче...",30,2.0,"[{'name': 'Пельмени', 'qty': '600', 'grams': '...","{'Калории': '120,18', 'Белки': '5,41', 'Жиры':...",Нет,вторые блюда
25,25,Тунец на гриле с лимоном,https://food.ru/recipes/254953-tunec-na-grile-...,Лучше всего размораживать филе на нижней полке...,25,2.0,"[{'name': 'Тунец', 'qty': '400', 'grams': '400...","{'Калории': '161,91', 'Белки': '13,25', 'Жиры'...","Белок коровьего молока, Рыба",вторые блюда
26,26,Гречка с болгарским перцем,https://food.ru/recipes/257038-grechka-s-bolga...,Залейте гречневую крупу водой в кастрюле и пос...,30,2.0,"[{'name': 'Сливочное масло', 'qty': '2', 'gram...","{'Калории': '107,38', 'Белки': '2,85', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глютен",вторые блюда
27,27,Салат с куриными сердечками,https://food.ru/recipes/254893-Salat-s-kurinym...,Очистите сердечки от пленок и жира. Разрежьте ...,10,2.0,"[{'name': 'Нектарин', 'qty': '1.5', 'grams': '...","{'Калории': '156,2', 'Белки': '5,92', 'Жиры': ...",Кунжут,вторые блюда
28,28,Оладьи из кабачка и курицы,https://food.ru/recipes/256836-oladi-iz-kabach...,Крупно натрите кабачок в миску. Дайте постоять...,40,8.0,"[{'name': 'Куриное филе', 'qty': '400', 'grams...","{'Калории': '127,33', 'Белки': '10,05', 'Жиры'...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
29,29,Минтай в кляре на сковороде,https://food.ru/recipes/256648-mintai-v-kljare...,"Как разморозить рыбу так, чтобы она сохранила ...",30,3.0,"[{'name': 'Филе минтая', 'qty': '600', 'grams'...","{'Калории': '155,09', 'Белки': '13,96', 'Жиры'...","Злаки, содержащие глютен, Рыба, Яйцо",вторые блюда
30,30,Куриные сердечки в сметане,https://food.ru/recipes/254891-kurinye-serdech...,Произвольно нарежьте картофель и переложите в ...,30,3.0,"[{'name': 'Куриные сердечки', 'qty': '500', 'g...","{'Калории': '134,84', 'Белки': '5,68', 'Жиры':...","Белок коровьего молока, Орехи",вторые блюда
31,31,Куриная печень с черносливом,https://food.ru/recipes/254890-kurinaja-pechen...,"Нарежьте лук и морковь мелкими кубиками, а лук...",30,3.0,"[{'name': 'Куриная печень', 'qty': '500', 'gra...","{'Калории': '171,59', 'Белки': '10,47', 'Жиры'...",Белок коровьего молока,вторые блюда
32,32,Равиоли с творожным сыром,https://food.ru/recipes/256553-ravioli-s-tvoro...,Смешайте муку с солью. Разбейте к ним яйца. За...,65,4.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '285,92', 'Белки': '9,21', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
33,33,Очень сырные макароны со шпинатом,https://food.ru/recipes/256552-ochen-slivochno...,Вместо сотейника также можно взять кастрюлю с ...,30,6.0,"[{'name': 'Паста', 'qty': '450', 'grams': '450...","{'Калории': '209,33', 'Белки': '9,26', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
34,34,Чесночные спагетти со стейком,https://food.ru/recipes/256937-chesnochnye-spa...,Отварите спагетти в подсоленной воде в течение...,20,2.0,"[{'name': 'Спагетти', 'qty': '225', 'grams': '...","{'Калории': '174,8', 'Белки': '3,73', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
35,35,Стейк с кофейной корочкой,https://food.ru/recipes/256964-steik-s-kofeino...,"Соедините в небольшой пиале молотый кофе, трос...",70,2.0,"[{'name': 'Говяжий стейк рибай', 'qty': '2', '...","{'Калории': '250,02', 'Белки': '17,01', 'Жиры'...",Белок коровьего молока,вторые блюда
36,36,Рыба в сырном кляре,https://food.ru/recipes/256952-ryba-v-syrnom-k...,Промокните рыбу от влаги бумажными полотенцами...,30,2.0,"[{'name': 'Треска', 'qty': '1', 'grams': '300'...","{'Калории': '222,48', 'Белки': '13,94', 'Жиры'...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
37,37,Стейк с маслом «Кафе де Пари»,https://food.ru/recipes/256963-steik-s-maslom-...,"Промокните стейк бумажным полотенцем, чтобы из...",90,2.0,"[{'name': 'Виски', 'qty': '1', 'grams': '18'},...","{'Калории': '365,67', 'Белки': '10,83', 'Жиры'...","Белок коровьего молока, Горчица, Пищевые добав...",вторые блюда
38,38,Стейк денвер с соусом ромеско и огуречным салатом,https://food.ru/recipes/256935-steik-denver-s-...,Разложите перцы и помидоры на противне. Сделай...,65,4.0,"[{'name': 'Оливковое масло', 'qty': '2', 'gram...","{'Калории': '103,88', 'Белки': '5,72', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
39,39,Стейк в стиле «Вода и земля»,https://food.ru/recipes/256927-steik-v-stile-v...,"Как разморозить креветки без вреда для вкуса, ...",40,2.0,"[{'name': 'Сливочное масло', 'qty': '40', 'gra...","{'Калории': '235,62', 'Белки': '14,61', 'Жиры'...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
40,40,Стейк фланк со сладким перцем,https://food.ru/recipes/256918-flank-steik-so-...,"Оберните каждый стейк пергаментом, отбейте кух...",140,2.0,"[{'name': 'Стейк фланк', 'qty': '2', 'grams': ...","{'Калории': '214,38', 'Белки': '12,6', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
41,41,Ризотто с куриной печенью,https://food.ru/recipes/254845-rizotto-s-kurin...,Застелите противень пекарской бумагой и выложи...,70,2.0,"[{'name': 'Куриная печень', 'qty': '500', 'gra...","{'Калории': '156,81', 'Белки': '9,67', 'Жиры':...","Белок коровьего молока, Пищевые добавки",вторые блюда
42,42,Сэндвич со стейком,https://food.ru/recipes/256967-sendvich-so-ste...,Посыпьте стейки со всех сторон черным перцем. ...,100,2.0,"[{'name': 'Стейк «Канзас»', 'qty': '600', 'gra...","{'Калории': '265,64', 'Белки': '13,05', 'Жиры'...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
43,43,Нежные паровые фрикадельки,https://food.ru/recipes/256084-nezhnye-frikadelki,Добавьте творог к фаршу.\nЧтобы фрикадельки по...,40,1.0,"[{'name': 'Куриный фарш', 'qty': '100', 'grams...","{'Калории': '199,04', 'Белки': '14,41', 'Жиры'...","Белок коровьего молока, Яйцо",вторые блюда
44,44,Топ-блейд с брусничным соусом,https://food.ru/recipes/256915-top-bleid-s-bru...,"Выложите замороженную бруснику в сотейник, нал...",270,2.0,"[{'name': 'Стейк «Топ Блейд»', 'qty': '500', '...","{'Калории': '48,53', 'Белки': '0,3', 'Жиры': '...",Нет,вторые блюда
45,45,Цыпленок с апельсинами,https://food.ru/recipes/254792-cyplenok-s-apel...,Растопите масло в большой сковороде. Выложите ...,40,4.0,"[{'name': 'Цыпленок', 'qty': '1', 'grams': '10...","{'Калории': '186,72', 'Белки': '14,09', 'Жиры'...",Белок коровьего молока,вторые блюда
46,46,Деруны с салом,https://food.ru/recipes/256516-deruny-s-salom,"Натрите картофель, лук и морковь на крупной те...",30,6.0,"[{'name': 'Картошка', 'qty': '5', 'grams': '60...","{'Калории': '212,08', 'Белки': '3,19', 'Жиры':...","Злаки, содержащие глютен, Яйцо",вторые блюда
47,47,Пеппер-стейк,https://food.ru/recipes/256924-Pepper-steik,Нарежьте лук-шалот кубиками со стороной 3–4 мм...,100,2.0,"[{'name': 'Черный перец молотый', 'qty': '2', ...","{'Калории': '113,37', 'Белки': '10,4', 'Жиры':...",Белок коровьего молока,вторые блюда
48,48,Яичница по-кабардински,https://food.ru/recipes/256514-jaichnica-po-ka...,"Поставьте сухую сковороду на слабый огонь, нал...",10,1.0,"[{'name': 'Сметана 20% жирности', 'qty': '4', ...","{'Калории': '175,96', 'Белки': '7,93', 'Жиры':...","Белок коровьего молока, Яйцо",вторые блюда
49,49,Сашими из семги,https://food.ru/recipes/254789-sashimi-iz-semgi,Для чистки имбиря используйте ложку — аккуратн...,135,1.0,"[{'name': 'Филе лосося', 'qty': '100', 'grams'...","{'Калории': '234,15', 'Белки': '8,76', 'Жиры':...","Злаки, содержащие глютен, Кунжут, Рыба, Соя",вторые блюда

In [44]:
# final_df.to_csv('recipes_foodru_2.csv', index=False, encoding='utf-8-sig')

Убираем нерабочее

In [37]:
# df1_no_id = df1.reset_index(drop=True)
# df_final_no_id = final_df.reset_index(drop=True)
# 
# df = pd.concat([df1_no_id, df_final_no_id], ignore_index=True)
# df['id'] = df.index + 1

In [6]:
df = pd.read_csv('recipes_foodru.csv')
df.head(100)

,id,title,url,recipe,time,count,ingredients,nutrients,allergy,category
0,1,Сырный суп со скумбрией,https://food.ru/recipes/227818-syrnyi-sup-so-s...,Нарежьте бекон на небольшие кусочки. Разогрейт...,30,4.0,"[{'name': 'Консервированная скумбрия', 'qty': ...","{'Калории': '202,74', 'Белки': '12,75', 'Жиры'...","Белок коровьего молока, Ракообразные, Рыба",первые блюда
1,2,Густой суп из шампиньонов с сыром и брокколи,https://food.ru/recipes/176803-sup-iz-gribov-s...,Нарежьте шампиньоны пластинками. Обжарьте в ма...,30,3.0,"[{'name': 'Шампиньоны', 'qty': '4', 'grams': '...","{'Калории': '28,68', 'Белки': '1,33', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глютен",первые блюда
2,3,Как сварить любой суп,https://food.ru/recipes/197715-kak-svarit-liub...,"Положите в кастрюлю кусок мяса, залейте водой ...",100,4.0,"[{'name': 'Свинина на кости', 'qty': '300', 'g...","{'Калории': '165,85', 'Белки': '7,59', 'Жиры':...","Злаки, содержащие глютен",первые блюда
3,4,Суп из сома,https://food.ru/recipes/228166-sup-iz-soma,Положите стейки сома в кастрюлю. Вскипятите в ...,40,3.0,"[{'name': 'Сом морской', 'qty': '300', 'grams'...","{'Калории': '33,69', 'Белки': '2,12', 'Жиры': ...","Злаки, содержащие глютен, Рыба",первые блюда
4,5,Татарская лапша,https://food.ru/recipes/228087-tatarskaja-lapsha,"Взбейте куриные яйца с 0,5 ч.л. соли при помощ...",180,4.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '55,03', 'Белки': '3,73', 'Жиры': ...","Злаки, содержащие глютен, Яйцо",первые блюда
...,...,...,...,...,...,...,...,...,...,...
95,96,Зеленые щи со щавелем,https://food.ru/recipes/214572-zelnye-shchi-s-...,Положите говядину в кастрюлю. Залейте водой и ...,130,4.0,"[{'name': 'Щавель', 'qty': '300', 'grams': '30...","{'Калории': '50,53', 'Белки': '1,77', 'Жиры': ...","Белок коровьего молока, Яйцо",первые блюда
96,97,Сырный суп с овощами,https://food.ru/recipes/213865-ovoshchnoi-syrn...,Нарежьте картофель и морковь кубиками со сторо...,45,3.0,"[{'name': 'Плавленый сыр', 'qty': '100', 'gram...","{'Калории': '30,2', 'Белки': '1,6', 'Жиры': '0...",Белок коровьего молока,первые блюда
97,98,Пшенный суп с курицей,https://food.ru/recipes/213864-pshennyi-sup-s-...,"Положите куриный окорочок в кастрюлю, залейте ...",50,3.0,"[{'name': 'Куриный окорочок', 'qty': '300', 'g...","{'Калории': '44,21', 'Белки': '2,78', 'Жиры': ...",Нет,первые блюда
98,99,Суп с ячневой крупой,https://food.ru/recipes/213814-sup-s-jachnevoi...,Разрежьте куриные крылья на несколько частей. ...,75,4.0,"[{'name': 'Вода', 'qty': '2', 'grams': '2000'}...","{'Калории': '37,14', 'Белки': '2,45', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глютен",первые блюда
99,100,Венгерский мясной суп,https://food.ru/recipes/212846-vengerskii-mjas...,Измельчите курдючный жир на маленькие кусочки....,115,6.0,"[{'name': 'Баранина', 'qty': '400', 'grams': '...","{'Калории': '89,12', 'Белки': '3,72', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глютен",первые блюда

In [7]:
df.tail(20)

,id,title,url,recipe,time,count,ingredients,nutrients,allergy,category
4801,4802,Треска с картофелем и розмарином,https://food.ru/recipes/231064-treska-s-kartof...,Нарежьте картофель небольшими дольками. Положи...,45,3.0,"[{'name': 'Филе трески', 'qty': '600', 'grams'...","{'Калории': '98,21', 'Белки': '8,1', 'Жиры': '...","Белок коровьего молока, Горчица, Рыба",вторые блюда
4802,4803,Курица по-тоскански,https://food.ru/recipes/231141-Kurica-po-toska...,"Разрежьте каждое куриное филе на две половины,...",45,6.0,"[{'name': 'Куриное филе', 'qty': '500', 'grams...","{'Калории': '108,21', 'Белки': '9,43', 'Жиры':...","Белок коровьего молока, Пищевые добавки",вторые блюда
4803,4804,Пикантная сливочная лапша с креветками,https://food.ru/recipes/231045-pikantnaja-sliv...,Выложите креветки в миску. Добавьте к ним 1 ст...,60,2.0,"[{'name': 'Креветки', 'qty': '500', 'grams': '...","{'Калории': '185,05', 'Белки': '13,83', 'Жиры'...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
4804,4805,Плов с яблоками,https://food.ru/recipes/231362-plov-s-jablokami,"Влейте в кастрюлю 1,25 стакана воды и всыпьте ...",70,4.0,"[{'name': 'Рис', 'qty': '90', 'grams': '90'}, ...","{'Калории': '116,59', 'Белки': '1,22', 'Жиры':...",Орехи,вторые блюда
4805,4806,Рыбные котлеты с зеленым пюре,https://food.ru/recipes/231103-rybnye-kotlety-...,Вскипятите в кастрюле воду с веточкой мяты. По...,25,2.0,"[{'name': 'Горох', 'qty': '1.5', 'grams': '307...","{'Калории': '42,22', 'Белки': '4,98', 'Жиры': ...","Белок коровьего молока, Рыба",вторые блюда
4806,4807,Индийское карри из хека,https://food.ru/recipes/231102-karri-iz-heka,"Снимите цедру с лаймов, измельчите ее. Разрежь...",120,4.0,"[{'name': 'Филе хека', 'qty': '600', 'grams': ...","{'Калории': '118,96', 'Белки': '7,74', 'Жиры':...","Пищевые добавки, Рыба",вторые блюда
4807,4808,Запеканка из овсянки с тыквой,https://food.ru/recipes/230665-ovsjanka-s-tykvoi,Нарежьте тыкву на небольшие кусочки и положите...,60,4.0,"[{'name': 'Тыква', 'qty': '250', 'grams': '250...","{'Калории': '144,34', 'Белки': '4,85', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
4808,4809,Морковные драники,https://food.ru/recipes/230589-morkovnye-draniki,"Натрите морковь на средней терке, пармезан — н...",40,3.0,"[{'name': 'Морковь', 'qty': '250', 'grams': '2...","{'Калории': '190,5', 'Белки': '6,78', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
4809,4810,Ньокки из картофеля,https://food.ru/recipes/230530-nki,"Положите картофель в кастрюлю, залейте водой. ...",50,2.0,"[{'name': 'Картошка', 'qty': '2', 'grams': '24...","{'Калории': '179,68', 'Белки': '8,99', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
4810,4811,Наггетсы из куриной грудки,https://food.ru/recipes/230528-naggetsy-iz-kur...,Хорошенько отбейте куриное филе с двух сторон ...,110,2.0,"[{'name': 'Куриное филе', 'qty': '450', 'grams...","{'Калории': '175,42', 'Белки': '18,22', 'Жиры'...","Белок коровьего молока, Злаки, содержащие глютен",вторые блюда
4811,4812,Быстрый жюльен с курицей и грибами,https://food.ru/recipes/231025-bystryi-zhulen-...,Нарежьте шампиньоны пластинками толщиной 2-3 м...,40,2.0,"[{'name': 'Рулет из мяса птицы', 'qty': '100',...","{'Калории': '174,13', 'Белки': '6,8', 'Жиры': ...",Белок коровьего молока,вторые блюда
4812,4813,Кета в кляре на сковороде,https://food.ru/recipes/230481-keta-v-kljare-n...,"Смешайте сметану с горчицей, солью и перцем. Р...",30,2.0,"[{'name': 'Филе кеты', 'qty': '300', 'grams': ...","{'Калории': '221,49', 'Белки': '14,17', 'Жиры'...","Белок коровьего молока, Горчица, Злаки, содерж...",вторые блюда
4813,4814,Тыквенное суфле,https://food.ru/recipes/230472-tykvennoe-sufle,Срежьте у тыквы кожуру. Мякоть овоща нарежьте ...,65,2.0,"[{'name': 'Тыква', 'qty': '200', 'grams': '200...","{'Калории': '61,58', 'Белки': '2,96', 'Жиры': ...","Белок коровьего молока, Яйцо",вторые блюда
4814,4815,Драники из капусты,https://food.ru/recipes/230466-draniki-iz-kapusty,Тонко нашинкуйте капусту. Выложите в глубокую ...,40,4.0,"[{'name': 'Капуста', 'qty': '500', 'grams': '5...","{'Калории': '131,05', 'Белки': '3,32', 'Жиры':...","Злаки, содержащие глютен, Яйцо",вторые блюда
4815,4816,Картофельная бабка с салом,https://food.ru/recipes/231027-kartofelnaja-ba...,Крупно натрите картофель в миску. Присыпьте ег...,64,2.0,"[{'name': 'Свиное сало', 'qty': '150', 'grams'...","{'Калории': '276,37', 'Белки': '2,08', 'Жиры':...","Белок коровьего молока, Злаки, содержащие глютен",вторые блюда
4816,4817,Вкусные суши с лососем,https://food.ru/recipes/49009-sushi-s-lososem,Отварите рис и добавьте соус «Сушидзу». Дайте ...,15,1.0,"[{'name': 'Рис', 'qty': '80', 'grams': '80'}, ...","{'Калории': '233,65', 'Белки': '12,56', 'Жиры'...",Рыба,вторые блюда
4817,4818,"Запеканка с морковью, грудинкой и брокколи",https://food.ru/recipes/231024-zapekanka-s-mor...,Разделите брокколи на соцветия размером около ...,55,2.0,"[{'name': 'Варено-копченая грудинка', 'qty': '...","{'Калории': '95,77', 'Белки': '4,15', 'Жиры': ...","Белок коровьего молока, Пищевые добавки, Яйцо",вторые блюда
4818,4819,Куриные кнели,https://food.ru/recipes/230333-kurinyi-muss,Разделите белки и желтки в разные миски. Взбей...,55,2.0,"[{'name': 'Куриное филе', 'qty': '400', 'grams...","{'Калории': '66,99', 'Белки': '5,97', 'Жиры': ...","Белок коровьего молока, Орехи, Сельдерей, Яйцо",вторые блюда
4819,4820,Куриные шницели со сливочно-сырным соусом,https://food.ru/recipes/230207-kotlety-pod-sousom,Разрежьте каждый кусок куриного филе на две од...,25,4.0,"[{'name': 'Куриное филе', 'qty': '400', 'grams...","{'Калории': '190,94', 'Белки': '13,18', 'Жиры'...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда
4820,4821,Творожная запеканка с маком,https://food.ru/recipes/229837-tvorozhnaja-zap...,Насыпьте в небольшую миску мак. Вскипятите вод...,60,4.0,"[{'name': 'Творог 5%', 'qty': '450', 'grams': ...","{'Калории': '170,32', 'Белки': '12,49', 'Жиры'...","Белок коровьего молока, Злаки, содержащие глют...",вторые блюда

In [42]:
df.to_csv('recipes_foodru.csv', index=False, encoding='utf-8-sig')

Код обработки для эмбеддингов

In [4]:
# from nltk.corpus import stopwords, wordnet
# from nltk.stem import WordNetLemmatizer
# import nltk
# import warnings
# 
# warnings.filterwarnings('ignore')
# 
# # Скачиваем словари при первом запуске
# nltk.download('punkt', quiet=True)
# nltk.download('stopwords', quiet=True)
# nltk.download('wordnet', quiet=True)
# 
# STOPWORDS = set(stopwords.words('english'))
# lemmatizer = WordNetLemmatizer()
# 
# 
# # Функция для определения части речи
# def get_wordnet_pos(word):
#     tag = nltk.pos_tag([word])[0][1][0].upper()
#     tag_dict = {
#         'J': wordnet.ADJ,
#         'N': wordnet.NOUN,
#         'V': wordnet.VERB,
#         'R': wordnet.ADV
#     }
#     return tag_dict.get(tag, wordnet.NOUN)
# 
# 
# # Предобработка запроса теми же шагами
# def preprocess_query(q: str):
#     # В нижний шрифт
#     text = q.lower()
#     # Убираем markdown и ссылки
#     text = re.sub(r'[^a-z0-9\u0400-\u04FF\s]', ' ', text)
#     # Преобразуем в начальную форму
#     tokens = [lemmatizer.lemmatize(tok, get_wordnet_pos(tok)) for tok in text.split() if tok not in STOPWORDS and len(tok) > 2]
#     return ' '.join(tokens), tokens

In [8]:
import spacy

nlp = spacy.load("ru_core_news_md")

def preprocess_query(text: str):
    doc = nlp(text.lower())
    tokens = [
        token.lemma_ 
        for token in doc 
        if not token.is_stop and not token.is_punct and len(token.text) > 2
    ]
    return ' '.join(tokens), tokens

In [9]:
print(preprocess_query('Куриное филе с помидорами и специями.'))

('куриный филе помидор специя', ['куриный', 'филе', 'помидор', 'специя'])

Работаем с ингредиентами

In [10]:
from ast import literal_eval
df['ingredients'] = df['ingredients'].apply(literal_eval)

In [11]:
# df['ingredients_names_eng'] =

In [12]:
df['ingredients_per_one'] = df.apply(
    lambda row: [
        {
            'name': preprocess_query(item['name'])[0],
            'qty': round(float((item.get('qty') or '0').replace(',', '.')) / row['count'], 2),
            'grams': round(float((item.get('grams') or '0').replace(',', '.')) / row['count'])
        }
        for item in row['ingredients']
    ],
    axis=1
)
df.head()

,id,title,url,recipe,time,count,ingredients,nutrients,allergy,category,ingredients_per_one
0,1,Сырный суп со скумбрией,https://food.ru/recipes/227818-syrnyi-sup-so-s...,Нарежьте бекон на небольшие кусочки. Разогрейт...,30,4.0,"[{'name': 'Консервированная скумбрия', 'qty': ...","{'Калории': '202,74', 'Белки': '12,75', 'Жиры'...","Белок коровьего молока, Ракообразные, Рыба",первые блюда,"[{'name': 'консервированный скумбрия', 'qty': ..."
1,2,Густой суп из шампиньонов с сыром и брокколи,https://food.ru/recipes/176803-sup-iz-gribov-s...,Нарежьте шампиньоны пластинками. Обжарьте в ма...,30,3.0,"[{'name': 'Шампиньоны', 'qty': '4', 'grams': '...","{'Калории': '28,68', 'Белки': '1,33', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глютен",первые блюда,"[{'name': 'шампиньон', 'qty': 1.33, 'grams': 4..."
2,3,Как сварить любой суп,https://food.ru/recipes/197715-kak-svarit-liub...,"Положите в кастрюлю кусок мяса, залейте водой ...",100,4.0,"[{'name': 'Свинина на кости', 'qty': '300', 'g...","{'Калории': '165,85', 'Белки': '7,59', 'Жиры':...","Злаки, содержащие глютен",первые блюда,"[{'name': 'свинина кость', 'qty': 75.0, 'grams..."
3,4,Суп из сома,https://food.ru/recipes/228166-sup-iz-soma,Положите стейки сома в кастрюлю. Вскипятите в ...,40,3.0,"[{'name': 'Сом морской', 'qty': '300', 'grams'...","{'Калории': '33,69', 'Белки': '2,12', 'Жиры': ...","Злаки, содержащие глютен, Рыба",первые блюда,"[{'name': 'сом морской', 'qty': 100.0, 'grams'..."
4,5,Татарская лапша,https://food.ru/recipes/228087-tatarskaja-lapsha,"Взбейте куриные яйца с 0,5 ч.л. соли при помощ...",180,4.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '55,03', 'Белки': '3,73', 'Жиры': ...","Злаки, содержащие глютен, Яйцо",первые блюда,"[{'name': 'пшеничная мука хлебопекарный', 'qty..."

In [13]:
df['ingredients_names'] = df['ingredients'].apply(
    lambda items: "; ".join(preprocess_query(item['name'])[0] for item in items)
)
df.head()

,id,title,url,recipe,time,count,ingredients,nutrients,allergy,category,ingredients_per_one,ingredients_names
0,1,Сырный суп со скумбрией,https://food.ru/recipes/227818-syrnyi-sup-so-s...,Нарежьте бекон на небольшие кусочки. Разогрейт...,30,4.0,"[{'name': 'Консервированная скумбрия', 'qty': ...","{'Калории': '202,74', 'Белки': '12,75', 'Жиры'...","Белок коровьего молока, Ракообразные, Рыба",первые блюда,"[{'name': 'консервированный скумбрия', 'qty': ...",консервированный скумбрия; сладкий перец; поми...
1,2,Густой суп из шампиньонов с сыром и брокколи,https://food.ru/recipes/176803-sup-iz-gribov-s...,Нарежьте шампиньоны пластинками. Обжарьте в ма...,30,3.0,"[{'name': 'Шампиньоны', 'qty': '4', 'grams': '...","{'Калории': '28,68', 'Белки': '1,33', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глютен",первые блюда,"[{'name': 'шампиньон', 'qty': 1.33, 'grams': 4...",шампиньон; картошка; плавленый сыр; морковь; б...
2,3,Как сварить любой суп,https://food.ru/recipes/197715-kak-svarit-liub...,"Положите в кастрюлю кусок мяса, залейте водой ...",100,4.0,"[{'name': 'Свинина на кости', 'qty': '300', 'g...","{'Калории': '165,85', 'Белки': '7,59', 'Жиры':...","Злаки, содержащие глютен",первые блюда,"[{'name': 'свинина кость', 'qty': 75.0, 'grams...",свинина кость; соль; морковь; растительный мас...
3,4,Суп из сома,https://food.ru/recipes/228166-sup-iz-soma,Положите стейки сома в кастрюлю. Вскипятите в ...,40,3.0,"[{'name': 'Сом морской', 'qty': '300', 'grams'...","{'Калории': '33,69', 'Белки': '2,12', 'Жиры': ...","Злаки, содержащие глютен, Рыба",первые блюда,"[{'name': 'сом морской', 'qty': 100.0, 'grams'...",сом морской; картошка; репчатый лук; морковь; ...
4,5,Татарская лапша,https://food.ru/recipes/228087-tatarskaja-lapsha,"Взбейте куриные яйца с 0,5 ч.л. соли при помощ...",180,4.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '55,03', 'Белки': '3,73', 'Жиры': ...","Злаки, содержащие глютен, Яйцо",первые блюда,"[{'name': 'пшеничная мука хлебопекарный', 'qty...",пшеничная мука хлебопекарный; куриный яйцо; со...

In [14]:
df['ingredients_names_grams'] = df['ingredients_per_one'].apply(
    lambda items: "; ".join(f"{preprocess_query(item['name'])[0]}: {item['grams']} г" for item in items)
)
df.head()

,id,title,url,recipe,time,count,ingredients,nutrients,allergy,category,ingredients_per_one,ingredients_names,ingredients_names_grams
0,1,Сырный суп со скумбрией,https://food.ru/recipes/227818-syrnyi-sup-so-s...,Нарежьте бекон на небольшие кусочки. Разогрейт...,30,4.0,"[{'name': 'Консервированная скумбрия', 'qty': ...","{'Калории': '202,74', 'Белки': '12,75', 'Жиры'...","Белок коровьего молока, Ракообразные, Рыба",первые блюда,"[{'name': 'консервированный скумбрия', 'qty': ...",консервированный скумбрия; сладкий перец; поми...,консервированный скумбрия: 60 г; сладкий перец...
1,2,Густой суп из шампиньонов с сыром и брокколи,https://food.ru/recipes/176803-sup-iz-gribov-s...,Нарежьте шампиньоны пластинками. Обжарьте в ма...,30,3.0,"[{'name': 'Шампиньоны', 'qty': '4', 'grams': '...","{'Калории': '28,68', 'Белки': '1,33', 'Жиры': ...","Белок коровьего молока, Злаки, содержащие глютен",первые блюда,"[{'name': 'шампиньон', 'qty': 1.33, 'grams': 4...",шампиньон; картошка; плавленый сыр; морковь; б...,шампиньон: 43 г; картошка: 40 г; плавленый сыр...
2,3,Как сварить любой суп,https://food.ru/recipes/197715-kak-svarit-liub...,"Положите в кастрюлю кусок мяса, залейте водой ...",100,4.0,"[{'name': 'Свинина на кости', 'qty': '300', 'g...","{'Калории': '165,85', 'Белки': '7,59', 'Жиры':...","Злаки, содержащие глютен",первые блюда,"[{'name': 'свинина кость', 'qty': 75.0, 'grams...",свинина кость; соль; морковь; растительный мас...,свинина кость: 75 г; соль: 0 г; морковь: 25 г;...
3,4,Суп из сома,https://food.ru/recipes/228166-sup-iz-soma,Положите стейки сома в кастрюлю. Вскипятите в ...,40,3.0,"[{'name': 'Сом морской', 'qty': '300', 'grams'...","{'Калории': '33,69', 'Белки': '2,12', 'Жиры': ...","Злаки, содержащие глютен, Рыба",первые блюда,"[{'name': 'сом морской', 'qty': 100.0, 'grams'...",сом морской; картошка; репчатый лук; морковь; ...,сом морской: 100 г; картошка: 80 г; репчатый л...
4,5,Татарская лапша,https://food.ru/recipes/228087-tatarskaja-lapsha,"Взбейте куриные яйца с 0,5 ч.л. соли при помощ...",180,4.0,"[{'name': 'Пшеничная мука хлебопекарная', 'qty...","{'Калории': '55,03', 'Белки': '3,73', 'Жиры': ...","Злаки, содержащие глютен, Яйцо",первые блюда,"[{'name': 'пшеничная мука хлебопекарный', 'qty...",пшеничная мука хлебопекарный; куриный яйцо; со...,пшеничная мука хлебопекарный: 49 г; куриный яй...

## Добавление в ChromaDB

для обновления, снести бд и рестартнуть ядро

In [15]:
model = st.SentenceTransformer('paraphrase-multilingual-mpnet-base-v2')

In [18]:
def add_to_chroma(df: pd.DataFrame, collection_name='chroma_db'):
    chroma = chromadb.PersistentClient(path=collection_name)
    
    # try:
    #     chroma.delete_collection(name=collection_name)
    # except ValueError:
    #     print(f"Коллекция '{collection_name}' не найдена, будет создана новая.")
        
        
    coll   = chroma.get_or_create_collection(
        name=collection_name,
        metadata={"hnsw:space": "cosine"}
    )

    docs       = df['ingredients_names'].tolist()
    embeds     = model.encode(docs, batch_size=64, show_progress_bar=True, normalize_embeddings=True)
    meta  = df[
        ['title', 'recipe', 'time', 'count', 'allergy', 'nutrients', 'ingredients', 'ingredients_per_one']
    ].to_dict(orient='records')
    
    for rec in meta:
        rec['ingredients'] = json.dumps(rec['ingredients'], ensure_ascii=False)
        rec['ingredients_per_one'] = json.dumps(rec['ingredients_per_one'], ensure_ascii=False)

    coll.add(
        documents = docs,
        ids       = df['id'].astype(str).tolist(),
        metadatas = meta,
        embeddings= embeds
    )
    
    print('Vectors in Chroma:', coll.count())

In [19]:
add_to_chroma(df, collection_name='chroma_db')

Batches: 100%|██████████| 76/76 [00:22<00:00,  3.34it/s]

Vectors in Chroma: 4821

## Поиск по базе

In [20]:
def embed_inventory(inv: dict[str,int]):
    text = "; ".join(preprocess_query(k)[0] for k, v in inv.items())
    return model.encode([text], normalize_embeddings=True)[0]

def retrieve_candidates(inv, topN=100, collection_name='chroma_db'):
    emb = embed_inventory(inv)
    chroma = chromadb.PersistentClient(path=collection_name)
    coll   = chroma.get_or_create_collection(collection_name)
    
    res = coll.query(
        query_embeddings=[emb.tolist()],
        n_results=topN,
        # where=where,
        include=['documents', 'metadatas', 'distances'],
    )
    return res

UNIT2G = {'г': 1, 'мл': 1, 'шт.': 60, 'стакан': 200, 'ст. л.': 18}
def coverage(recipe_ingrs: str, inv: list) -> float:
    items = json.loads(recipe_ingrs)
    got, total = 0, len(items)
    for ingr in items:
        # print(f"Checking ingredient: {ingr}")
        # по граммам
        # have = inv.get(name, 0) * UNIT2G.get('шт.',1)
        # if have >= need_g:
        #     got += 1
        
        # по названию
        name_cleaned = preprocess_query(ingr['name'])[0]
        # print(f"Checking {ingr['name']} in inventory...")
        if name_cleaned in inv:
            got += 1
    return got / total if total else 0

In [21]:
def top_k(inv: dict, k: int = 10, pool: int = 100):
    cand = retrieve_candidates(inv, topN=pool)
    print(f"Found {len(cand['documents'][0])}")
    
    # scored = []
    # inv_cleaned = [preprocess_query(k)[0] for k in inv.keys()]
    # print(f"Inventory cleaned: {inv_cleaned}")
    # for meta, doc in zip(cand['metadatas'][0], cand['documents'][0]):
    #     # print(f'Meta {meta}, doc {doc}')
    #     cov = coverage(meta['ingredients'], inv_cleaned)
    #     scored.append((cov, doc, meta))
    # scored.sort(key=lambda x: (-x[0], ))      # ↓ по coverage
    # return scored[:k]

    combined = zip(cand['distances'][0], cand['metadatas'][0])
    scored = sorted(combined, key=lambda x: x[0])

    return [meta for _, meta in scored[:k]]

Пример

In [25]:
inv = {
    'куриное филе': 2,
    'помидоры': 3,
    'лук': 3,
    'чеснок': 5,
    'оливковое масло': 1,
    'специи': 1
}

res = top_k(inv, k=3)
for meta in res:
    print(f"title: {meta['title']}, time: {meta['time']} мин")
    print(f"ingredients: {meta['ingredients']}")
    print(f"allergy: {meta['allergy']}")
    print(f"nutrients: {meta['nutrients']}")
    print()

Found 100
title: Аппетитное чахохбили с пряными куриными крылышками по-домашнему, time: 60 мин
ingredients: [{"name": "Куриные крылышки", "qty": "1500", "grams": "1500"}, {"name": "Репчатый лук", "qty": "300", "grams": "300"}, {"name": "Помидор", "qty": "320", "grams": "320"}, {"name": "Чеснок", "qty": "10", "grams": "10"}, {"name": "Соль", "qty": null, "grams": null}, {"name": "Кинза", "qty": null, "grams": null}, {"name": "Черный перец молотый", "qty": null, "grams": null}, {"name": "Сливочное масло", "qty": null, "grams": null}, {"name": "Томатный соус", "qty": "40", "grams": "40"}]
allergy: Белок коровьего молока
nutrients: {'Калории': '140,18', 'Белки': '13,69', 'Жиры': '8,61', 'Углеводы': '2,2'}

title: Сочное чахохбили из курицы с пряным соевым соусом, овощами и специями, time: 60 мин
ingredients: [{"name": "Курица", "qty": "1500", "grams": "1500"}, {"name": "Репчатый лук", "qty": "300", "grams": "300"}, {"name": "Помидор", "qty": "250", "grams": "250"}, {"name": "Соевый соус", "qty": "60", "grams": "60"}, {"name": "Чеснок", "qty": "10", "grams": "10"}, {"name": "Соль", "qty": null, "grams": null}, {"name": "Кинза", "qty": null, "grams": null}, {"name": "Черный перец молотый", "qty": null, "grams": null}, {"name": "Растительное масло", "qty": "30", "grams": "30"}, {"name": "Томатный соус", "qty": "40", "grams": "40"}]
allergy: Злаки, содержащие глютен, Соя
nutrients: {'Калории': '154,51', 'Белки': '11,56', 'Жиры': '11,14', 'Углеводы': '2,2'}

title: Сочное чахохбили в фольге, time: 80 мин
ingredients: [{"name": "Курица", "qty": "2000", "grams": "2000"}, {"name": "Растительное масло", "qty": "4", "grams": "68"}, {"name": "Соль", "qty": "10", "grams": "10"}, {"name": "Паприка", "qty": "5", "grams": "5"}, {"name": "Чеснок", "qty": "20", "grams": "20"}, {"name": "Черный перец молотый", "qty": "5", "grams": "5"}, {"name": "Помидор", "qty": "350", "grams": "350"}, {"name": "Сушеный тимьян / чабрец", "qty": "5", "grams": "5"}]
allergy: Нет
nutrients: {'Калории': '184,44', 'Белки': '13,27', 'Жиры': '14,21', 'Углеводы': '0,97'}